feat(compiler): expand table expression to its columns
ibis-project/ibis-substrait pull request #185
Opened 2022-05-01 12:51 UTC by rtpsw

See https://github.com/ibis-project/ibis-substrait/issues/184

2022-05-01 12:54 UTC, rtpsw commented
Note that one alternative is to make the table expansion a choice controlled by a parameter of `ibis.mutate` placed in a member of `ops.Selection`.

2022-05-01 15:33 UTC, cpcloud requested changes
@rtpsw Can you add a test for this change?

2022-05-01 15:33 UTC, cpcloud commented on ibis_substrait/compiler/translate.py
> +        for x in (s.get_columns(s.columns) if isinstance(s, ir.TableExpr) else [s])
```suggestion
        col
        for sel in op.selections
        for col in (sel.get_columns(sel.columns) if isinstance(sel, ir.TableExpr) else [sel])
```

2022-05-02 15:28 UTC, rtpsw commented
> @rtpsw Can you add a test for this change?

Will do.

2022-05-10 19:52 UTC, cpcloud commented
@rtpsw This looks reasonable to me.

2022-05-10 19:52 UTC, cpcloud approved these changes
LGTM, just needs a squash then it's good to go.

2022-05-11 11:48 UTC, merged