Expose extension uri parameter in SubstraitCompiler
ibis-project/ibis-substrait pull request #99
Opened 2022-03-08 08:14 UTC by rtpsw

2022-03-08 12:36 UTC, cpcloud requested changes

2022-03-08 12:36 UTC, cpcloud commented on ibis_substrait/compiler/core.py
> +    def __init__(self, uri: str = None) -> None:
```suggestion
    def __init__(self, uri: str | None = None) -> None:
```

2022-03-08 12:37 UTC, cpcloud commented
@rtpsw Can you fixup and change the commit to match the PR title (I changed the PR title).

2022-03-11 12:35 UTC, rtpsw commented
@cpcloud, is anything remaining after the recent commit?

2022-03-29 12:32 UTC, rtpsw commented
@cpcloud: is this ready to be merged?

2022-03-29 14:14 UTC, cpcloud commented
@rtpsw Can you squash to a single commit matching the PR title?

2022-03-30 18:07 UTC, rtpsw commented
I opted to add a commit with this comment and with an addition doc. I believe GH should allow you to squash using this comment.

2022-03-30 18:30 UTC, rtpsw commented
Last commit fixes a [lint error](https://github.com/ibis-project/ibis-substrait/runs/5738580590?check_suite_focus=true).

2022-04-01 16:02 UTC, rtpsw commented
@cpcloud: Hopefully I have the commit as required now.

2022-04-01 18:56 UTC, rtpsw commented
To keep things simple, I created a clean PR https://github.com/ibis-project/ibis-substrait/pull/137 to replace this PR.

2022-04-01 18:57 UTC, rtpsw commented
Canceling this.

2022-04-01 18:57 UTC, closed without merging